version: '3.9'

services:
    
  simple-webapp:
    ports:
      - "80" 
    
    container_name: youtubecloneflexcompletelatest
    build:
      context: .
      dockerfile: Dockerfile.dev

    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: ["npm", "run", "test",]
  
