version: '3.9'

services:

  simple-webapp:
    container_name: youtubecloneflexcomplete


    build:
      context: .
      dockerfile: Dockerfile.dev

      volunes:
        -  ./:/app
        -  /app/node_modules

      ports:
        - "8001:8000"
