version: '3.9'

services:
  backend:
    container_name: backend
    image: ipkyle/ytbackend-dev-latest:latest
    ports:
      - "80:8000"
    command: sh ./entrypoint.sh

  
  db:
    container_name: kylewiseKaw
    image: mysql
    
    environment:
      MYSQL_DATABASE: 'youtube_clone_database'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping","-h", "localhost"]
      timeout: 20s
      retries: 10
    volumes:
      - production_db_volume:/var/lib/mysql 
volumes:
  production_db_volume: